create table if not exists public.annotations (
  id bigint generated by default as identity primary key,
  owner uuid not null references auth.users(id) on delete cascade,
  owner_email text not null,
  chapter_id text not null,
  paragraph_id text,
  kind text not null check (kind in ('note', 'plan', 'revision')),
  content text not null,
  image_key text,
  image_name text,
  is_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists annotations_chapter_idx
on public.annotations(chapter_id, updated_at desc);

create table if not exists public.reading_progress (
  owner uuid primary key references auth.users(id) on delete cascade,
  chapter_id text not null,
  paragraph_id text,
  updated_at timestamptz not null default now()
);

alter table public.annotations enable row level security;
alter table public.reading_progress enable row level security;

create policy "anyone reads public notes"
on public.annotations for select
using (is_public or owner = auth.uid());

create policy "owner inserts own content"
on public.annotations for insert
with check (
  owner = auth.uid()
  and lower(owner_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  and lower(owner_email) = lower('18968565068@163.com')
);

create policy "owner updates own content"
on public.annotations for update
using (owner = auth.uid())
with check (owner = auth.uid());

create policy "owner deletes own content"
on public.annotations for delete
using (owner = auth.uid());

create policy "owner reads progress"
on public.reading_progress for select
using (owner = auth.uid());

create policy "owner inserts progress"
on public.reading_progress for insert
with check (owner = auth.uid());

create policy "owner updates progress"
on public.reading_progress for update
using (owner = auth.uid())
with check (owner = auth.uid());

insert into storage.buckets (id, name, public)
values ('book-images', 'book-images', false)
on conflict (id) do nothing;

create policy "owner uploads book images"
on storage.objects for insert
with check (
  bucket_id = 'book-images'
  and (storage.foldername(name))[1] = auth.uid()::text
  and lower(coalesce(auth.jwt() ->> 'email', '')) = lower('18968565068@163.com')
);

create policy "visible annotation images"
on storage.objects for select
using (
  bucket_id = 'book-images'
  and exists (
    select 1 from public.annotations a
    where a.image_key = name and (a.is_public or a.owner = auth.uid())
  )
);

create policy "owner deletes book images"
on storage.objects for delete
using (
  bucket_id = 'book-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);
